### ISSUE TITLE
Transfers - Silver & Core

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#18]
We need a silver layer for **Token Transfers** with a core view. This table will be downstream of the messages model (#8 ) and should focus on the movement of tokens between accounts when they are transferred.

## TODO

- [ ] Assign primary & secondary analysts
- [ ] Design the schema for this table
- [ ] Get confirmation on schema
- [ ] Build schema
- [ ] Schema build review
- [ ] Submit Pull Request for review by pod

## Direction
Token Transfers is a common curated table and many examples can be found in the Flipside data tables, most notably Terra Classic and Osmosis, as other Tendermint representatives.

Per the IBC Lite Mode document, suggested schema includes the following tables:
| Column          | Data Type | Tests                                          | Documentation                                                                                                                                                                                                                                           |
|-----------------|-----------|------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| block_id        | number    | Unique, not null, sequence gaps, number format | Also known as block height. The block_id, which indicates the length of the blockchain, increases after the addition of each new block.                                                                                                                 |
| block_timestamp | timestamp | One day recent, not null, timestamp format     | The date and time the block was recorded.                                                                                                                                                                                                               |
| blockchain      | string    | not null, string/varchar format                | The name of the blockchain.                                                                                                                                                                                                                             |
| chain_id        | string    | not null, string/varchar format                | The version of the blockchain.                                                                                                                                                                                                                          |
| tx_id           | string    | not null, string/varchar format                | A unique key that identifies a transaction. Called "TxHash" on block explorers.                                                                                                                                                                         |
| tx_succeeded    | boolean   | not null                                       | TRUE if the transaction was successful, FALSE otherwise.                                                                                                                                                                                                |
| transfer_type   | string    | not null, string/varchar format                | Details on the type of transfer occurring during the transaction. "IBC_Transfer_In" = transferring tokens to the blockchain, "IBC_Transfer_Off" = transferring tokens from the blockchain to another, "blockchain name" = wallet to wallet on the chain |
| sender          | string    | not null, string/varchar format                | The wallet address of the user that initiated the transfer                                                                                                                                                                                              |
| amount          | number    | not null, number format                        | The non-decimal adjusted amount of currency being sent.                                                                                                                                                                                                 |
| currency        | string    | not null, string/varchar format                | An address representing the token being sent. Join to labels for name / symbol                                                                                                                                                                          |
| decimal         | number    | not null, number format                        | Divide amount by decimal to get the actual amount of currency being transferred.                                                                                                                                                                        |
| receiver        | string    | not null, string/varchar format                | The wallet address that is receiving the transfer.                                                                                                                                                                                                      |


On review of the Terra Classic, and available data, possible additional columns are:
- event_type
- address_name
- label_sub_type
- contract_address

## Contribution Reward
Per the S3 approach, this falls into the project category and contribution incentive will be handled through [Coordinape](https://coordinape.com/). Expected collaboration is 3-4 individuals with a primary Analyst, primary PR Reviewer and possible secondaries for either the Analyst or Review side of the work.

**Issue reward pool:** $1,200 in LUNA (token amount determined at time of payment)

**Comment by D0R11** [comment]
will be taking this one

**Comment by robel91** [comment]
@forgxyz can I be assigned as secondary analyst here instead?
