### ISSUE TITLE
Staking - Silver & Core

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#19]
We need a silver layer for **Staking Activities** with a core view. This table will be downstream of the messages model (#8 ) and should focus on delegation undelegation, and redelegation actions.

## TODO

- [ ] Assign primary & secondary analysts
- [ ] Design the schema for this table
- [ ] Get confirmation on schema
- [ ] Build schema
- [ ] Schema build review
- [ ] Submit Pull Request for review by pod

## Direction
Token Transfers is a common curated table and many examples can be found in the Flipside data tables, most notably Terra Classic and Osmosis, as other Tendermint representatives.

This table should be as close to the `TERRA.CLASSIC.EZ_STAKING` schema as possible, barring any data changes from Columbus-5 to Phoenix-1.

Proposed Schema for CORE

- ACTION
- BLOCK_ID
- BLOCK_TIMESTAMP
- BLOCKCHAIN
- CHAIN_ID
- CURRENCY
- DELEGATOR_ADDRESS
- _DELEGATOR_ADDRESS_LABEL_
  - _Labels for Phoenix-1 are limited and these above may not be possible_
- EVENT_AMOUNT
- MSG_INDEX
- TX_ID
- TX_STATUS
- VALIDATOR_ADDRESS
- _VALIDATOR_ADDRESS_LABEL_
    - _Labels for Phoenix-1 are limited and these above may not be possible_

## Contribution Reward
Per the S3 approach, this falls into the project category and contribution incentive will be handled through [Coordinape](https://coordinape.com/). Expected collaboration is 3-4 individuals with a primary Analyst, primary PR Reviewer and possible secondaries for either the Analyst or Review side of the work.

**Issue reward pool:** $1,200 in LUNA (token amount determined at time of payment)

**Comment by robel91** [comment]
I can take this one
