### ISSUE TITLE
Blocks - Silver + Core

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#2]
We need a silver layer for blocks with a core view. 

Essential components for this first layer are:
- [x] Deduplication. Chainwalkers will include duplicates, so we need to ensure the initial `silver__blocks` model only has 1 record per block.
- [x] Incremental macro
- [x] Gap tests
- [x] Recency tests
- [x] Uniqueness / no dupes test

## TODO

- [x] Design the schema for this table
- [x] Get confirmation on schema
- [x] Build schema
- [x] Schema build review
- [x] Submit Pull Request for review by pod

**Comment by geewynn** [comment]
I will be working on this.

**Comment by geewynn** [comment]
Proposed Schema design

- block_id,
- block_timestamp,
- block_hash,
- chain_id,
- consensus_hash,
- data_hash,
- evidence,
- evidence_hash,
- block_height,
- last_block_id,
- last_commit,
- last_commit_hash,
- last_results_hash,
- next_validators_hash,
- proposer_address,
- validators_hash

**Comment by forgxyz** [comment]
I like this schema @geewynn 
Is there anything in the block header / metadata we are dropping or choosing not to include? Otherwise, I say we move forward with the build.

**Comment by geewynn** [comment]
> 
yes, I omitted this, didn't really know if it was going to be needed.
```
"version": {
      "app": null,
      "block": "11"
    }
```

**Comment by forgxyz** [comment]
Ok, agree that that is not needed.
One thing I am used to seeing with other chains is `tx_count`  - is that available anywhere in the header? If not, alright to proceed.

**Comment by geewynn** [comment]
It is available and i have added it to the schema. Missed it in the first schema build.
