### ISSUE TITLE
Transactions - Silver + Core

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#3]
We need a silver layer for transactions with a core view. 

Essential components for this first layer are:
- [x] Deduplication. Chainwalkers will include duplicates, so we need to ensure the initial `silver__transactions` model only has 1 record per transaction.
- [x] Incremental Macro
- [x] Gap tests
- [x] Recency tests
- [x] Uniqueness / no dupes test

## TODO

- [x] Design the schema for this table
- [x] Get confirmation on schema
- [x] Build schema
- [ ] Schema build review
- [ ] Submit Pull Request for review by pod

**Comment by forgxyz** [comment]
Initial Schema:

- tx_id,
- block_id,
- block_timestamp,
- network,
- chain_id,
- pub_key,
- gas_limit,
- fee_raw,
- fee_denom,
- memo,
- tx,
- _ingested_at,
- _inserted_timestamp

The [terra.js](https://docs.terra.money/develop/terra-js/keys) docs include how to decode the public key into the actual address, which would give us the sender of the tx. This is to be added to the model.

In core - the tx fee paid will be decimal adjusted, to be left as raw in silver.
