### ISSUE TITLE
Messages - Silver & Core

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#8]
We need a silver layer for messages with a core view. This table will be downstream of the `transactions` model and should focus on parsing the messages that happen in each event, to provide the data in an easy-to-use format. Each message should be a record in the table, and transactions may have several messages per tx.

## TODO

- [x] Assign primary & secondary analysts
- [x] Design the schema for this table
- [x] Get confirmation on schema
- [x] Build schema
- [ ] Schema build review
- [ ] Submit Pull Request for review by pod

## Direction
The structure of the messages is up to the analysts and will evolve through exploration. You can look at the terra classic data on Flipside for inspiration.

Within the `tx` object, there is an array `tx:body:messages` with data that Terrascope mirrors as the top-level message data. Using an [example tx](https://terrasco.pe/mainnet/tx/734E008C554C1941822E3879A4FD3F964535B35DEF6F8887C8C55B6BAF937E78):

```
    "messages": [
      {
        "@type": "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
        "delegator_address": "terra1u3ra7h5g7qqkpxvyy8wychgf76hha4stajvwe7",
        "validator_address": "terravaloper1v6pfkm0nxpudgantwxwhz786l8me0wfs4lnpuw"
      }
    ],
```

While the logs within `tx_result` contain step-level data within the message
```
   "log": [
      {
        "events": [
          {
            "attributes": [
              {
                "key": "receiver",
                "value": "terra1u3ra7h5g7qqkpxvyy8wychgf76hha4stajvwe7"
              },
              {
                "key": "amount",
                "value": "3778658uluna"
              }
            ],
            "type": "coin_received"
          },
          {
            "attributes": [ ...
```

**Comment by forgxyz** [comment]
Per 9/27 Sync, @geewynn is taking primary analyst on this. 
Secondary is open for any interested party.

**Comment by forgxyz** [comment]
It looks like on failed transactions, attributes is not decoded into logs.

Ex: D43B91472F248B49083B5794B6DA03C35A23F80065D0B40B536070A60120EF23

**Comment by forgxyz** [comment]
Within the `log` of successful transactions, the events/attributes for each event seem to be identified by `"msg_index": 0` within the object. We can use this to link messages in the body to events & event attributes within the result.

**Comment by D0R11** [comment]
> Within the `log` of successful transactions, the events/attributes for each event seem to be identified by `"msg_index": 0` within the object. We can use this to link messages in the body to events & event attributes within the result.

Will `message_events` be a separate table like the terra classic one? Or for this iteration, they're combined into `messages`?

**Comment by forgxyz** [comment]
We discussed, so just adding for posterity, but the message events will be combined into `messages`.
